version: "3.8"

services:
  backend:
    build:
      context: ./kahoot-clone-backend
      dockerfile: Dockerfile
    container_name: kahoot-backend
    ports:
      - "8000:8000"
    environment:
      - RUST_LOG=info
    restart: unless-stopped

  frontend:
    build:
      context: ./kahoot-clone-frontend
      dockerfile: Dockerfile
    container_name: kahoot-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
